final List<List<String>> longestCommonPrefixUseCase = [
  [""],
  ["plena", "pleb", "plent"],
  ["car", "careful", "carbon", "card"],
  ["sun", "sunrise", "sunset", "sundown", "sunflower"],
  ["trail"],
  ["alpha", "alphabet"],
  ["blue"],
  ["friend", "freak", "free"],
  ["cloud", "clout", "clove"],
  ["short", "shore", "shovel", "shone"],
  [""],
  ["mouse", "mountain", "mound", "mourn"],
  ["track"],
  ["spring", "sprite"],
  ["drift", "driver", "driveway", "driven"],
  ["rope", "roller"],
  [""],
  ["paint", "pane", "panic", "panel"],
  ["ocean", "octopus", "oxygen"],
  ["power", "powder", "poverty"],
  ["night", "nicer", "nickname"],
  ["hard", "harvest", "harmony", "harbor"],
  ["magic", "magnet", "magical"],
  ["castle", "cash"],
  ["world", "worker", "worry"],
  [""],
  ["grass", "gravel", "grave"],
  ["stone", "storm", "store", "stop"],
  ["water", "wave", "waste"],
  ["space", "span", "spark", "spare"],
  ["fresh", "frenzy"],
  ["dream", "drill"],
  ["travel", "trail"],
  ["green", "greet", "great"],
  [""],
  ["smart", "smarter", "smarmy"],
  ["quick", "quicker"],
  ["fire", "firm", "first"],
  ["cloud", "clover"],
  ["metal", "method", "meter", "metaphor"],
  ["clear", "clerk"],
  [""],
  ["giant", "gift", "giver", "giddy"],
  ["animal", "anchor", "angle", "annual"],
  ["trust", "truth", "trunk"],
  ["flower", "flour"],
  ["school", "scheme"],
  ["focus", "fog", "fold", "folly"],
  ["dance", "danger"],
  ["love", "lover", "lobby", "lone"],
  [""],
  ["mount", "mouse", "mouth", "mourn"],
  ["peace", "peanut", "peach", "peak"],
  ["money", "monk", "monitor", "moment"],
  ["train", "track", "trail"],
  ["winter", "winner", "window"],
  [""],
  ["apple", "applause", "apply"],
  ["code", "coder", "coding", "cold"],
  ["chair", "chain", "chalk"],
  ["sharp", "shard", "share", "shiny"],
  ["kind", "king", "kinship"],
  ["happy", "happen", "harmony", "hat"],
  ["jump", "jumper", "jumpsuit"],
  [""],
  ["track", "tractor", "trademark", "trap"],
  ["music", "museum", "musical"],
  ["white", "whiter", "wither"],
  ["better", "bench", "bend"],
  ["bright", "bring"],
  [""],
  ["grass", "grasp", "gravel"],
  ["magic", "magical"],
  ["fast", "faster", "fashion"],
  ["dream", "dreamer"],
  ["vision", "visual"],
  ["peace"],
  ["school", "schedule"],
  [""],
  ["trust", "truth"],
  ["stone", "store"],
  ["river", "rivet"],
  ["family", "famine"],
  ["build", "builder"],
  [""],
  ["fruit", "frost"],
  ["castle", "cash"],
  ["green", "greet"],
  ["money"],
  ["powerful", "poverty"],
  [""],
  ["short", "shore"],
  ["friend", "freeze"],
  ["fire", "firm"],
  ["bright"],
  ["focus"],
  ["flower"],
  [""],
  ["cloud"],
  ["track", "tractor"],
];
